from __future__ import annotations

import json

from ..io_utils import write_text
from ..models import AgentRequest, AgentResult
from .base import AgentAdapter


class MockAdapter(AgentAdapter):
    def available(self) -> bool:
        return True

    def run(self, request: AgentRequest) -> AgentResult:
        content = f"MOCK stage={request.stage} effort={request.effort}\n"
        if request.stage == "clarify":
            content += "READY_TO_GENERATE\n"
        elif request.stage == "sync-agent-instructions":
            hard_rules = []
            if "Default output review pass must proceed to export" in request.prompt:
                hard_rules.append("Default output review pass must proceed to export.")
            content = json.dumps(
                {
                    "rules": {
                        "hard_rules": hard_rules,
                        "workflow_contracts": [],
                        "engineering_validation": [],
                        "testing_contracts": [],
                    }
                },
                ensure_ascii=False,
                indent=2,
            )
        elif request.stage == "review":
            content = "DECISION: pass\nMock review passed.\n"
        elif request.stage == "readme":
            if "Do NOT write the README yet. Only outline the planned sections." in request.prompt:
                content = "- Overview\n- Architecture\n- Usage\n"
                write_text(request.output_path, content)
                streamed_stdout = False
                if request.stream_output is not None:
                    request.stream_output("stdout", content)
                    streamed_stdout = True
                return AgentResult(
                    ok=True,
                    command=["mock"],
                    output_path=request.output_path,
                    summary=content.strip(),
                    stdout=content,
                    returncode=0,
                    streamed_stdout=streamed_stdout,
                )
            use_chinese = "Simplified Chinese" in request.prompt
            readme = (
                "# Mock Project\n\n"
                "## 项目说明\n\n"
                "- 由 mock provider 生成的占位 README。\n\n"
                "## 项目架构\n\n"
                "- 使用单个 mock adapter 写入文件产物。\n\n"
                "## 使用说明\n\n"
                "```bash\n"
                "python -m auto_agents status --project .\n"
                "```\n"
                if use_chinese
                else
                "# Mock Project\n\n"
                "## Overview\n\n"
                "- Generated by the mock provider.\n\n"
                "## Architecture\n\n"
                "- Single mock adapter with file-based outputs.\n\n"
                "## Usage\n\n"
                "```bash\n"
                "python -m auto_agents status --project .\n"
                "```\n"
            )
            write_text(request.cwd / "README.md", readme)
            content = "Mock README updated.\n"
        write_text(request.output_path, content)
        streamed_stdout = False
        if request.stream_output is not None:
            request.stream_output("stdout", content)
            streamed_stdout = True
        return AgentResult(
            ok=True,
            command=["mock"],
            output_path=request.output_path,
            summary=content.strip(),
            stdout=content,
            returncode=0,
            streamed_stdout=streamed_stdout,
        )
