import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from auto_agents.agent_instructions import ensure_agent_instructions_synced, sync_agent_instructions
from auto_agents.config import agent_instructions_lock_path, project_rules_path
from auto_agents.io_utils import write_text
from auto_agents.models import TaskSpec
from auto_agents.orchestrator import Orchestrator


class AgentInstructionSyncTests(unittest.TestCase):
    @staticmethod
    def _commit_all(project_root: Path) -> None:
        subprocess.run(["git", "config", "user.name", "test"], cwd=str(project_root), check=True)
        subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=str(project_root), check=True)
        subprocess.run(["git", "add", "-A"], cwd=str(project_root), check=True)
        subprocess.run(["git", "commit", "-m", "baseline"], cwd=str(project_root), check=True)

    def test_init_syncs_default_instruction_files(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")

            self.assertTrue(project_rules_path(project_root).is_file())
            self.assertEqual(project_rules_path(project_root).read_text(encoding="utf-8"), "")
            agents = (project_root / "AGENTS.md").read_text(encoding="utf-8")
            copilot = (project_root / ".github" / "copilot-instructions.md").read_text(encoding="utf-8")
            path_rules = (
                project_root / ".github" / "instructions" / "project.instructions.md"
            ).read_text(encoding="utf-8")
            self.assertIn("Generated by auto_agents sync-agent-instructions", agents)
            self.assertIn("Prefer small, directly verifiable changes", agents)
            self.assertIn("Additional path-specific rules", copilot)
            self.assertIn('applyTo: "**"', path_rules)

            lock = json.loads(agent_instructions_lock_path(project_root).read_text(encoding="utf-8"))
            self.assertIn("source_sha256", lock)
            self.assertIn("generated_sha256", lock)
            self.assertNotIn("generator_version", lock)

    def test_sync_combines_default_rules_with_meaningful_project_rules(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            write_text(
                project_rules_path(project_root),
                "- Default compose success path is output_review pass -> export.\n"
                "- Do not reintroduce a default output confirmation gate.\n",
            )

            result = sync_agent_instructions(project_root)

            self.assertTrue(result.synced)
            self.assertTrue(result.project_rules_meaningful)
            agents = (project_root / "AGENTS.md").read_text(encoding="utf-8")
            copilot = (project_root / ".github" / "copilot-instructions.md").read_text(encoding="utf-8")
            self.assertIn("Prefer small, directly verifiable changes", agents)
            self.assertIn("Default compose success path is output_review pass -> export", agents)
            self.assertIn("Do not reintroduce a default output confirmation gate", copilot)

    def test_unmeaningful_project_rules_fall_back_to_default_rules(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            write_text(project_rules_path(project_root), "todo\n")

            result = sync_agent_instructions(project_root)

            self.assertFalse(result.project_rules_meaningful)
            agents = (project_root / "AGENTS.md").read_text(encoding="utf-8")
            self.assertIn("No project-specific rules are currently defined", agents)
            self.assertNotIn("todo", agents)

    def test_ensure_resyncs_when_source_changes(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            write_text(project_rules_path(project_root), "- Keep exports automatic after output review passes.\n")

            result = ensure_agent_instructions_synced(project_root)

            self.assertTrue(result.synced)
            agents = (project_root / "AGENTS.md").read_text(encoding="utf-8")
            self.assertIn("Keep exports automatic", agents)

    def test_ensure_resyncs_when_generated_file_drifts(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            write_text(project_root / "AGENTS.md", "manual edit\n")

            result = ensure_agent_instructions_synced(project_root)

            self.assertTrue(result.synced)
            agents = (project_root / "AGENTS.md").read_text(encoding="utf-8")
            self.assertIn("Generated by auto_agents sync-agent-instructions", agents)
            self.assertNotIn("manual edit", agents)

    def test_task_clean_tree_check_ignores_generated_instruction_files(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            self._commit_all(project_root)
            write_text(project_root / "AGENTS.md", "generated drift\n")

            orchestrator = Orchestrator(project_root)
            orchestrator._require_clean_tree_for_task(
                TaskSpec(task_id="task-001", title="demo", description="demo", acceptance=["done"])
            )


if __name__ == "__main__":
    unittest.main()
