import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from auto_agents.agent_instructions import ensure_agent_instructions_synced, sync_agent_instructions
from auto_agents.config import agent_instructions_lock_path, project_rules_path
from auto_agents.io_utils import write_text
from auto_agents.models import TaskSpec
from auto_agents.orchestrator import Orchestrator


class AgentInstructionSyncTests(unittest.TestCase):
    @staticmethod
    def _commit_all(project_root: Path) -> None:
        subprocess.run(["git", "config", "user.name", "test"], cwd=str(project_root), check=True)
        subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=str(project_root), check=True)
        subprocess.run(["git", "add", "-A"], cwd=str(project_root), check=True)
        subprocess.run(["git", "commit", "-m", "baseline"], cwd=str(project_root), check=True)

    def test_init_syncs_default_instruction_files(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")

            self.assertTrue(project_rules_path(project_root).is_file())
            self.assertEqual(project_rules_path(project_root).read_text(encoding="utf-8"), "")
            agents = (project_root / "AGENTS.md").read_text(encoding="utf-8")
            copilot = (project_root / ".github" / "copilot-instructions.md").read_text(encoding="utf-8")
            path_rules = (
                project_root / ".github" / "instructions" / "product-contract.instructions.md"
            ).read_text(encoding="utf-8")
            self.assertIn("Generated by auto_agents sync-agent-instructions", agents)
            self.assertIn("Prefer small, directly verifiable changes", agents)
            self.assertIn("Additional path-specific rules", copilot)
            self.assertIn('applyTo: "app/**,tests/**,specs/**"', path_rules)

            lock = json.loads(agent_instructions_lock_path(project_root).read_text(encoding="utf-8"))
            self.assertIn("source_sha256", lock)
            self.assertIn("generated_sha256", lock)
            self.assertNotIn("generator_version", lock)

    def test_sync_combines_default_rules_with_meaningful_project_rules(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            write_text(
                project_rules_path(project_root),
                "- Default compose success path is output_review pass -> export.\n"
                "- Do not reintroduce a default output confirmation gate.\n",
            )

            result = sync_agent_instructions(project_root)

            self.assertTrue(result.synced)
            self.assertTrue(result.project_rules_meaningful)
            agents = (project_root / "AGENTS.md").read_text(encoding="utf-8")
            copilot = (project_root / ".github" / "copilot-instructions.md").read_text(encoding="utf-8")
            self.assertIn("Prefer small, directly verifiable changes", agents)
            self.assertIn("Default compose success path is output_review pass -> export", agents)
            self.assertIn("Do not reintroduce a default output confirmation gate", copilot)

    def test_unmeaningful_project_rules_fall_back_to_default_rules(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            write_text(project_rules_path(project_root), "todo\n")

            result = sync_agent_instructions(project_root)

            self.assertFalse(result.project_rules_meaningful)
            agents = (project_root / "AGENTS.md").read_text(encoding="utf-8")
            self.assertIn("No project-specific rules are currently defined", agents)
            self.assertNotIn("todo", agents)

    def test_ensure_resyncs_when_source_changes(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            write_text(project_rules_path(project_root), "- Keep exports automatic after output review passes.\n")

            result = ensure_agent_instructions_synced(project_root)

            self.assertTrue(result.synced)
            agents = (project_root / "AGENTS.md").read_text(encoding="utf-8")
            self.assertIn("Keep exports automatic", agents)

    def test_ensure_resyncs_when_generated_file_drifts(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            write_text(project_root / "AGENTS.md", "manual edit\n")

            result = ensure_agent_instructions_synced(project_root)

            self.assertTrue(result.synced)
            agents = (project_root / "AGENTS.md").read_text(encoding="utf-8")
            self.assertIn("Generated by auto_agents sync-agent-instructions", agents)
            self.assertNotIn("manual edit", agents)

    def test_task_clean_tree_check_ignores_generated_instruction_files(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            self._commit_all(project_root)
            write_text(project_root / "AGENTS.md", "generated drift\n")

            orchestrator = Orchestrator(project_root)
            orchestrator._require_clean_tree_for_task(
                TaskSpec(task_id="task-001", title="demo", description="demo", acceptance=["done"])
            )

    def test_sync_extracts_rules_instead_of_copying_long_source(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            long_background = "背景说明：" + ("这些内容只是给人阅读的解释。" * 80)
            write_text(
                project_rules_path(project_root),
                "# Video Flow Contract\n\n"
                f"{long_background}\n\n"
                "默认模式下，输出审核通过后必须直接进入 export，不需要额外人工确认输出。\n"
                "系统不再把 process_review 作为独立的产品审核阶段。\n"
                "中间过程只做工程校验，不能使用 pass/review/block 审核语义。\n"
                "测试必须遵守产品合同，不能继续期待 awaiting_output_confirmation 作为默认路径。\n",
            )

            sync_agent_instructions(project_root)

            agents = (project_root / "AGENTS.md").read_text(encoding="utf-8")
            product_rules = (
                project_root / ".github" / "instructions" / "product-contract.instructions.md"
            ).read_text(encoding="utf-8")
            self.assertIn("输出审核通过后必须直接进入 export", agents)
            self.assertIn("process_review", product_rules)
            self.assertIn("测试必须遵守产品合同", product_rules)
            self.assertNotIn("这些内容只是给人阅读的解释" * 5, agents)
            self.assertLess(len((project_root / ".github" / "copilot-instructions.md").read_text(encoding="utf-8")), 1800)

    def test_sync_combines_result_intro_with_following_enum_values(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            write_text(
                project_rules_path(project_root),
                "输入审核结果只能是：\n\n"
                "- `pass`\n"
                "- `review`\n"
                "- `block`\n\n"
                "默认合同规定：`pass` 后直接进入 `export`。\n",
            )

            sync_agent_instructions(project_root)

            agents = (project_root / "AGENTS.md").read_text(encoding="utf-8")
            product_rules = (
                project_root / ".github" / "instructions" / "product-contract.instructions.md"
            ).read_text(encoding="utf-8")
            self.assertIn("输入审核结果只能是: pass, review, block", agents)
            self.assertIn("默认合同规定：pass 后直接进入 export", product_rules)
            self.assertNotIn("输入审核结果只能是：\n\nSee", agents)

    def test_sync_combines_general_intro_lists_and_skips_stage_labels(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            write_text(
                project_rules_path(project_root),
                "默认仍保留三个人工确认点：\n\n"
                "- 确认规划\n"
                "- 确认资产\n"
                "- 确认分镜\n\n"
                "也就是说，默认合同是：\n\n"
                "```text\noutput_review pass -> export\n```\n\n"
                "这两步都必须以真实模型能力落地。\n"
                "当前用户真正关心的是“输入能不能生成”和“最终成片能不能交付”\n"
                "输出审核 output_review\n"
                "最终导出 export\n",
            )

            sync_agent_instructions(project_root)

            agents = (project_root / "AGENTS.md").read_text(encoding="utf-8")
            product_rules = (
                project_root / ".github" / "instructions" / "product-contract.instructions.md"
            ).read_text(encoding="utf-8")
            self.assertIn("默认仍保留三个人工确认点: 确认规划, 确认资产, 确认分镜", agents)
            self.assertIn("输入审核和输出审核都必须以真实模型能力落地", agents)
            self.assertNotIn("也就是说，默认合同是", product_rules)
            self.assertNotIn("当前用户真正关心", product_rules)
            self.assertNotIn("- 输出审核 output_review", product_rules)
            self.assertNotIn("- 最终导出 export", product_rules)

    def test_sync_removes_legacy_generated_project_instruction_file(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            legacy = project_root / ".github" / "instructions" / "project.instructions.md"
            write_text(legacy, "<!-- Generated by auto_agents sync-agent-instructions. Edit .auto-agents/project-rules.md instead. -->\nold\n")

            sync_agent_instructions(project_root)

            self.assertFalse(legacy.exists())


if __name__ == "__main__":
    unittest.main()
