import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from auto_agents.agent_instructions import (
    ensure_agent_instructions_synced,
    load_current_normalized_project_rules,
    normalized_project_rules_current,
    normalized_project_rules_identifier_feedback,
    parse_normalized_project_rules_output,
    project_rules_source_sha256,
    sync_agent_instructions,
    write_normalized_project_rules,
)
from auto_agents.config import (
    agent_instructions_lock_path,
    load_project_config,
    normalized_project_rules_path,
    project_rules_path,
    save_project_config,
)
from auto_agents.io_utils import write_text
from auto_agents.models import AgentResult, TaskSpec
from auto_agents.orchestrator import Orchestrator


class RecordingNormalizeAdapter:
    def __init__(self, hard_rule: str = "Normalized output review pass proceeds directly to export.") -> None:
        self.hard_rule = hard_rule
        self.requests = []

    def available(self) -> bool:
        return True

    def run(self, request):
        self.requests.append(request)
        content = json.dumps(
            {
                "rules": {
                    "hard_rules": [self.hard_rule],
                    "workflow_contracts": ["output_review pass -> export"],
                    "engineering_validation": ["Intermediate artifacts must be structurally valid before composition."],
                    "testing_contracts": ["Tests must not expect awaiting_output_confirmation on the default path."],
                }
            },
            ensure_ascii=False,
        )
        write_text(request.output_path, content)
        return AgentResult(
            ok=True,
            command=["recording-normalize"],
            output_path=request.output_path,
            summary=content,
            stdout=content,
            returncode=0,
        )


class SequentialNormalizeAdapter:
    def __init__(self, payloads) -> None:
        self.payloads = list(payloads)
        self.requests = []

    def available(self) -> bool:
        return True

    def run(self, request):
        self.requests.append(request)
        index = min(len(self.requests) - 1, len(self.payloads) - 1)
        content = json.dumps(self.payloads[index], ensure_ascii=False)
        write_text(request.output_path, content)
        return AgentResult(
            ok=True,
            command=["sequential-normalize"],
            output_path=request.output_path,
            summary=content,
            stdout=content,
            returncode=0,
        )


class AgentInstructionSyncTests(unittest.TestCase):
    @staticmethod
    def _commit_all(project_root: Path) -> None:
        subprocess.run(["git", "config", "user.name", "test"], cwd=str(project_root), check=True)
        subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=str(project_root), check=True)
        subprocess.run(["git", "add", "-A"], cwd=str(project_root), check=True)
        subprocess.run(["git", "commit", "-m", "baseline"], cwd=str(project_root), check=True)

    def test_init_syncs_default_instruction_files(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")

            self.assertTrue(project_rules_path(project_root).is_file())
            self.assertEqual(project_rules_path(project_root).read_text(encoding="utf-8"), "")
            agents = (project_root / "AGENTS.md").read_text(encoding="utf-8")
            copilot = (project_root / ".github" / "copilot-instructions.md").read_text(encoding="utf-8")
            path_rules = (
                project_root / ".github" / "instructions" / "product-contract.instructions.md"
            ).read_text(encoding="utf-8")
            self.assertNotIn("Generated by auto_agents sync-agent-instructions", agents)
            self.assertNotIn("These instructions apply to", agents)
            self.assertIn("Prefer small, directly verifiable changes", agents)
            self.assertIn("Additional path-specific rules", copilot)
            self.assertIn('applyTo: "app/**,tests/**,specs/**"', path_rules)

            lock = json.loads(agent_instructions_lock_path(project_root).read_text(encoding="utf-8"))
            self.assertIn("source_sha256", lock)
            self.assertIn("generated_sha256", lock)
            self.assertNotIn("generator_version", lock)

    def test_sync_combines_default_rules_with_meaningful_project_rules(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            write_text(
                project_rules_path(project_root),
                "- Default compose success path is output_review pass -> export.\n"
                "- Do not reintroduce a default output confirmation gate.\n",
            )

            result = sync_agent_instructions(project_root)

            self.assertTrue(result.synced)
            self.assertTrue(result.project_rules_meaningful)
            agents = (project_root / "AGENTS.md").read_text(encoding="utf-8")
            copilot = (project_root / ".github" / "copilot-instructions.md").read_text(encoding="utf-8")
            self.assertIn("Prefer small, directly verifiable changes", agents)
            self.assertIn("Default compose success path is output_review pass -> export", agents)
            self.assertIn("Do not reintroduce a default output confirmation gate", copilot)

    def test_sync_uses_current_normalized_rules_when_present(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            write_text(
                project_rules_path(project_root),
                "A long human document says output review pass must continue to export.\n",
            )
            write_normalized_project_rules(
                project_root,
                source_sha256=project_rules_source_sha256(project_root),
                rules={
                    "hard_rules": ["Normalized contract: output_review pass must export immediately."],
                    "workflow_contracts": [],
                    "engineering_validation": [],
                    "testing_contracts": [],
                },
            )

            sync_agent_instructions(project_root)

            agents = (project_root / "AGENTS.md").read_text(encoding="utf-8")
            self.assertIn("Normalized contract: output_review pass must export immediately", agents)

    def test_parse_normalized_project_rules_output_accepts_fenced_json(self) -> None:
        payload = parse_normalized_project_rules_output(
            "```json\n"
            "{\n"
            '  "rules": {\n'
            '    "hard_rules": ["A"],\n'
            '    "workflow_contracts": ["B"],\n'
            '    "engineering_validation": ["C"],\n'
            '    "testing_contracts": ["D"]\n'
            "  }\n"
            "}\n"
            "```"
        )

        self.assertEqual(payload["hard_rules"], ["A"])
        self.assertEqual(payload["workflow_contracts"], ["B"])
        self.assertEqual(payload["engineering_validation"], ["C"])
        self.assertEqual(payload["testing_contracts"], ["D"])

    def test_orchestrator_normalizes_project_rules_with_sync_agent_instructions_effort(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            config = load_project_config(project_root)
            config.efforts["sync-agent-instructions"] = "max"
            save_project_config(project_root, config)
            write_text(
                project_rules_path(project_root),
                "默认 `output_review` 通过后必须直接进入 export，不能等待 `awaiting_output_confirmation`。\n",
            )
            adapter = RecordingNormalizeAdapter()
            orchestrator = Orchestrator(project_root)
            orchestrator.adapter = adapter

            result = orchestrator._ensure_agent_instructions_synced()

            self.assertTrue(result.synced)
            self.assertEqual(len(adapter.requests), 1)
            self.assertEqual(adapter.requests[0].stage, "normalize_project_rules")
            self.assertEqual(adapter.requests[0].effort, "max")
            self.assertIn("Preserve source identifiers", adapter.requests[0].prompt)
            self.assertIn("Never replace a source identifier", adapter.requests[0].prompt)
            self.assertTrue(normalized_project_rules_path(project_root).is_file())
            self.assertTrue(normalized_project_rules_current(project_root))
            normalized = load_current_normalized_project_rules(project_root)
            self.assertIsNotNone(normalized)
            self.assertIn(adapter.hard_rule, normalized["hard_rules"])
            lock = json.loads(agent_instructions_lock_path(project_root).read_text(encoding="utf-8"))
            self.assertIn(".auto-agents/project-rules.normalized.json", lock["generated_sha256"])
            agents = (project_root / "AGENTS.md").read_text(encoding="utf-8")
            self.assertIn(adapter.hard_rule, agents)

    def test_normalized_identifier_feedback_rejects_identifiers_missing_from_source(self) -> None:
        feedback = normalized_project_rules_identifier_feedback(
            source_text="默认合同是 `process_review` pass -> `output_review` pass -> export。\n",
            rules={
                "hard_rules": ["Do not keep `process_moderation` in the default path."],
                "workflow_contracts": ["`output_review` pass -> export."],
                "engineering_validation": [],
                "testing_contracts": [],
            },
        )

        self.assertIsNotNone(feedback)
        self.assertIn("process_moderation", feedback or "")
        self.assertNotIn("output_review", feedback or "")

    def test_orchestrator_retries_normalized_rules_that_invent_identifiers(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            write_text(
                project_rules_path(project_root),
                "默认合同是 `process_review` pass -> `output_review` pass -> export。\n"
                "不要把 `process_review` 作为独立产品审核阶段。\n",
            )
            adapter = SequentialNormalizeAdapter([
                {
                    "rules": {
                        "hard_rules": ["Do not keep `process_moderation` in the default path."],
                        "workflow_contracts": ["`input_moderation` pass -> `output_review` pass -> export."],
                        "engineering_validation": [],
                        "testing_contracts": [],
                    }
                },
                {
                    "rules": {
                        "hard_rules": ["Do not keep `process_review` as an independent product review stage."],
                        "workflow_contracts": ["`process_review` pass -> `output_review` pass -> export."],
                        "engineering_validation": [],
                        "testing_contracts": [],
                    }
                },
            ])
            orchestrator = Orchestrator(project_root)
            orchestrator.adapter = adapter

            result = orchestrator._ensure_agent_instructions_synced()

            self.assertTrue(result.synced)
            self.assertEqual(len(adapter.requests), 2)
            self.assertIn("process_moderation", adapter.requests[1].prompt)
            normalized = load_current_normalized_project_rules(project_root)
            self.assertIsNotNone(normalized)
            self.assertIn("process_review", "\n".join(normalized["hard_rules"] + normalized["workflow_contracts"]))
            self.assertNotIn("process_moderation", "\n".join(normalized["hard_rules"] + normalized["workflow_contracts"]))

    def test_orchestrator_reuses_current_normalized_rules_without_llm(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            write_text(
                project_rules_path(project_root),
                "默认 `output_review` 通过后必须直接进入 export，不能等待 `awaiting_output_confirmation`。\n",
            )
            adapter = RecordingNormalizeAdapter()
            orchestrator = Orchestrator(project_root)
            orchestrator.adapter = adapter
            orchestrator._ensure_agent_instructions_synced()

            result = orchestrator._ensure_agent_instructions_synced()

            self.assertFalse(result.synced)
            self.assertEqual(len(adapter.requests), 1)

    def test_orchestrator_refreshes_normalized_rules_when_source_changes(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            write_text(
                project_rules_path(project_root),
                "默认 `output_review` 通过后必须直接进入 export，不能等待 `awaiting_output_confirmation`。\n",
            )
            adapter = RecordingNormalizeAdapter("First normalized rule.")
            orchestrator = Orchestrator(project_root)
            orchestrator.adapter = adapter
            orchestrator._ensure_agent_instructions_synced()
            write_text(
                project_rules_path(project_root),
                "默认 `output_review` 通过后必须直接进入 export，不能等待 `awaiting_output_confirmation`。测试必须遵守该合同。\n",
            )
            adapter.hard_rule = "Second normalized rule."

            orchestrator._ensure_agent_instructions_synced()

            self.assertEqual(len(adapter.requests), 2)
            agents = (project_root / "AGENTS.md").read_text(encoding="utf-8")
            self.assertIn("Second normalized rule", agents)

    def test_orchestrator_refreshes_normalized_rules_when_generated_normalized_file_drifts(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            write_text(
                project_rules_path(project_root),
                "默认 `output_review` 通过后必须直接进入 export，不能等待 `awaiting_output_confirmation`。\n",
            )
            adapter = RecordingNormalizeAdapter("Original normalized rule.")
            orchestrator = Orchestrator(project_root)
            orchestrator.adapter = adapter
            orchestrator._ensure_agent_instructions_synced()
            write_text(normalized_project_rules_path(project_root), '{"rules": {"hard_rules": ["manual drift"]}}\n')
            adapter.hard_rule = "Refreshed normalized rule."

            orchestrator._ensure_agent_instructions_synced()

            self.assertEqual(len(adapter.requests), 2)
            normalized = load_current_normalized_project_rules(project_root)
            self.assertIsNotNone(normalized)
            self.assertIn("Refreshed normalized rule.", normalized["hard_rules"])

    def test_unmeaningful_project_rules_fall_back_to_default_rules(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            write_normalized_project_rules(
                project_root,
                source_sha256=project_rules_source_sha256(project_root),
                rules={
                    "hard_rules": ["stale normalized rule"],
                    "workflow_contracts": [],
                    "engineering_validation": [],
                    "testing_contracts": [],
                },
            )
            write_text(project_rules_path(project_root), "todo\n")

            result = sync_agent_instructions(project_root)

            self.assertFalse(result.project_rules_meaningful)
            self.assertFalse(normalized_project_rules_path(project_root).exists())
            agents = (project_root / "AGENTS.md").read_text(encoding="utf-8")
            self.assertIn("No project-specific rules are currently defined", agents)
            self.assertNotIn("todo", agents)
            self.assertNotIn("stale normalized rule", agents)

    def test_ensure_resyncs_when_source_changes(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            write_text(project_rules_path(project_root), "- Keep exports automatic after output review passes.\n")

            result = ensure_agent_instructions_synced(project_root)

            self.assertTrue(result.synced)
            agents = (project_root / "AGENTS.md").read_text(encoding="utf-8")
            self.assertIn("Keep exports automatic", agents)

    def test_ensure_resyncs_when_generated_file_drifts(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            write_text(project_root / "AGENTS.md", "manual edit\n")

            result = ensure_agent_instructions_synced(project_root)

            self.assertTrue(result.synced)
            agents = (project_root / "AGENTS.md").read_text(encoding="utf-8")
            self.assertIn("Project Agent Instructions", agents)
            self.assertNotIn("manual edit", agents)

    def test_render_prioritizes_workflow_and_testing_contracts_in_root_files(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            write_text(project_rules_path(project_root), "- meaningful project contract text for sync.\n")

            sync_agent_instructions(
                project_root,
                normalized_rules={
                    "hard_rules": [f"Must preserve invariant {index}." for index in range(12)],
                    "workflow_contracts": [
                        "Default success path must transition directly from review pass to export.",
                        "Do not route default success through awaiting confirmation.",
                    ],
                    "engineering_validation": [
                        "Validate artifacts exist before downstream stages consume them.",
                    ],
                    "testing_contracts": [
                        "Tests must assert review pass -> export as the default path.",
                    ],
                },
            )

            agents = (project_root / "AGENTS.md").read_text(encoding="utf-8")
            copilot = (project_root / ".github" / "copilot-instructions.md").read_text(encoding="utf-8")
            self.assertIn("review pass to export", agents)
            self.assertIn("review pass -> export", agents)
            self.assertIn("review pass to export", copilot)

    def test_product_contract_keeps_later_high_priority_workflow_rules(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            write_text(project_rules_path(project_root), "- meaningful project contract text for sync.\n")

            sync_agent_instructions(
                project_root,
                normalized_rules={
                    "hard_rules": ["Use the documented contract as the source of truth."],
                    "workflow_contracts": [
                        *[f"General workflow rule {index}." for index in range(10)],
                        "Default mode must transition directly from output_review pass to export.",
                        "Do not transition from output_review pass to awaiting_output_confirmation.",
                    ],
                    "engineering_validation": [],
                    "testing_contracts": [],
                },
            )

            product_rules = (
                project_root / ".github" / "instructions" / "product-contract.instructions.md"
            ).read_text(encoding="utf-8")
            self.assertIn("output_review pass to export", product_rules)
            self.assertIn("awaiting_output_confirmation", product_rules)

    def test_task_clean_tree_check_ignores_generated_instruction_files(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            self._commit_all(project_root)
            write_text(project_root / "AGENTS.md", "generated drift\n")

            orchestrator = Orchestrator(project_root)
            orchestrator._require_clean_tree_for_task(
                TaskSpec(task_id="task-001", title="demo", description="demo", acceptance=["done"])
            )

    def test_sync_extracts_rules_instead_of_copying_long_source(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            long_background = "背景说明：" + ("这些内容只是给人阅读的解释。" * 80)
            write_text(
                project_rules_path(project_root),
                "# Video Flow Contract\n\n"
                f"{long_background}\n\n"
                "默认模式下，输出审核通过后必须直接进入 export，不需要额外人工确认输出。\n"
                "系统不再把 process_review 作为独立的产品审核阶段。\n"
                "中间过程只做工程校验，不能使用 pass/review/block 审核语义。\n"
                "测试必须遵守产品合同，不能继续期待 awaiting_output_confirmation 作为默认路径。\n",
            )

            sync_agent_instructions(project_root)

            agents = (project_root / "AGENTS.md").read_text(encoding="utf-8")
            product_rules = (
                project_root / ".github" / "instructions" / "product-contract.instructions.md"
            ).read_text(encoding="utf-8")
            self.assertIn("输出审核通过后必须直接进入 export", agents)
            self.assertIn("process_review", product_rules)
            self.assertIn("测试必须遵守产品合同", product_rules)
            self.assertNotIn("这些内容只是给人阅读的解释" * 5, agents)
            self.assertLess(len((project_root / ".github" / "copilot-instructions.md").read_text(encoding="utf-8")), 1800)

    def test_sync_combines_result_intro_with_following_enum_values(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            write_text(
                project_rules_path(project_root),
                "输入审核结果只能是：\n\n"
                "- `pass`\n"
                "- `review`\n"
                "- `block`\n\n"
                "默认合同规定：`pass` 后直接进入 `export`。\n",
            )

            sync_agent_instructions(project_root)

            agents = (project_root / "AGENTS.md").read_text(encoding="utf-8")
            product_rules = (
                project_root / ".github" / "instructions" / "product-contract.instructions.md"
            ).read_text(encoding="utf-8")
            self.assertIn("输入审核结果只能是: pass, review, block", agents)
            self.assertIn("默认合同规定：pass 后直接进入 export", product_rules)
            self.assertNotIn("输入审核结果只能是：\n\nSee", agents)

    def test_sync_combines_general_intro_lists_and_skips_stage_labels(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            write_text(
                project_rules_path(project_root),
                "默认仍保留三个人工确认点：\n\n"
                "- 确认规划\n"
                "- 确认资产\n"
                "- 确认分镜\n\n"
                "也就是说，默认合同是：\n\n"
                "```text\noutput_review pass -> export\n```\n\n"
                "这两步都必须以真实模型能力落地。\n"
                "当前用户真正关心的是“输入能不能生成”和“最终成片能不能交付”\n"
                "输出审核 output_review\n"
                "最终导出 export\n",
            )

            sync_agent_instructions(project_root)

            agents = (project_root / "AGENTS.md").read_text(encoding="utf-8")
            product_rules = (
                project_root / ".github" / "instructions" / "product-contract.instructions.md"
            ).read_text(encoding="utf-8")
            self.assertIn("默认仍保留三个人工确认点: 确认规划, 确认资产, 确认分镜", agents)
            self.assertIn("输入审核和输出审核都必须以真实模型能力落地", agents)
            self.assertNotIn("也就是说，默认合同是", product_rules)
            self.assertNotIn("当前用户真正关心", product_rules)
            self.assertNotIn("- 输出审核 output_review", product_rules)
            self.assertNotIn("- 最终导出 export", product_rules)

    def test_sync_removes_legacy_generated_project_instruction_file(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project_root = Path(tmp) / "demo"
            Orchestrator.init_project(project_root, "demo", "mock")
            legacy = project_root / ".github" / "instructions" / "project.instructions.md"
            write_text(legacy, "<!-- Generated by auto_agents sync-agent-instructions. Edit .auto-agents/project-rules.md instead. -->\nold\n")

            sync_agent_instructions(project_root)

            self.assertFalse(legacy.exists())


if __name__ == "__main__":
    unittest.main()
