from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Sequence

from .config import agent_instructions_lock_path, project_rules_path
from .io_utils import read_json, read_text, write_json, write_text


MAX_ROOT_AGENTS_CHARS = 2800
MAX_COPILOT_ROOT_CHARS = 1800
MAX_PROJECT_INSTRUCTIONS_CHARS = 3600
MAX_RULE_CHARS = 220


DEFAULT_ENGINEERING_RULES = """# Project Agent Instructions

These instructions apply to Codex, GitHub Copilot CLI, and other coding agents working in this repository.

## Working Rules

- Treat the current repository as the only editable project unless the user explicitly says otherwise.
- Prefer small, directly verifiable changes over broad rewrites.
- Read the nearby implementation and tests before changing behavior.
- Preserve user changes and do not revert unrelated work.
- Keep generated runtime data under ignored temp/data directories, not tracked repo-root files.
- When changing behavior, update or add focused tests that prove the intended contract.
- Run the narrowest relevant verification first; run broader verification when the change touches shared behavior.
- If tests and product behavior disagree, identify the contract first instead of blindly changing tests.
"""


COPILOT_ROOT_RULES = """# Repository Instructions

- Work only inside this repository unless the user explicitly says otherwise.
- Keep changes focused and consistent with nearby code.
- Preserve unrelated user edits.
- Prefer owned, focused tests before broad verification.
- If a test conflicts with product behavior, resolve the product contract before changing expectations.
- Additional path-specific rules may exist in `.github/instructions/`.
"""


PRODUCT_CONTRACT_HEADER = """---
applyTo: "app/**,tests/**,specs/**"
---

# Product Contract Rules

Follow the repository rules in `AGENTS.md`. These project-specific rules are extracted from `.auto-agents/project-rules.md`.
"""


GENERATED_NOTICE = "<!-- Generated by auto_agents sync-agent-instructions. Edit .auto-agents/project-rules.md instead. -->"
GENERATED_AGENT_INSTRUCTION_PATHS = (
    "AGENTS.md",
    ".github/copilot-instructions.md",
    ".github/instructions/product-contract.instructions.md",
)
LEGACY_GENERATED_AGENT_INSTRUCTION_PATHS = (
    ".github/instructions/project.instructions.md",
)


@dataclass(frozen=True)
class AgentInstructionSyncResult:
    synced: bool
    source_path: str
    source_sha256: str
    generated_sha256: Dict[str, str]
    project_rules_meaningful: bool

    def to_dict(self) -> dict:
        return {
            "synced": self.synced,
            "source_path": self.source_path,
            "source_sha256": self.source_sha256,
            "generated_sha256": dict(self.generated_sha256),
            "project_rules_meaningful": self.project_rules_meaningful,
        }


def ensure_agent_instructions_synced(project_root: Path) -> AgentInstructionSyncResult:
    if _agent_instructions_current(project_root):
        return _sync_result_from_lock(project_root, synced=False)
    return sync_agent_instructions(project_root)


def sync_agent_instructions(project_root: Path) -> AgentInstructionSyncResult:
    root = project_root.resolve()
    source = project_rules_path(root)
    if not source.exists():
        write_text(source, "")

    raw_rules = read_text(source)
    project_rules = raw_rules.strip()
    meaningful = _meaningful_project_rules(project_rules)
    generated_files = _render_generated_files(project_rules if meaningful else "")

    generated_sha256: Dict[str, str] = {}
    for rel_path, content in generated_files.items():
        path = root / rel_path
        write_text(path, content)
        generated_sha256[rel_path] = _sha256_text(content)
    _remove_legacy_generated_files(root)

    source_sha = _sha256_bytes(source.read_bytes() if source.exists() else b"")
    lock_payload = {
        "source_sha256": source_sha,
        "generated_sha256": generated_sha256,
    }
    write_json(agent_instructions_lock_path(root), lock_payload)
    return AgentInstructionSyncResult(
        synced=True,
        source_path=_relative_path(root, source),
        source_sha256=source_sha,
        generated_sha256=generated_sha256,
        project_rules_meaningful=meaningful,
    )


def _agent_instructions_current(project_root: Path) -> bool:
    root = project_root.resolve()
    source = project_rules_path(root)
    lock = read_json(agent_instructions_lock_path(root), default=None)
    if not isinstance(lock, dict):
        return False
    if not source.exists():
        return False

    source_sha = _sha256_bytes(source.read_bytes())
    if str(lock.get("source_sha256", "")) != source_sha:
        return False

    generated = lock.get("generated_sha256", {})
    if not isinstance(generated, dict) or not generated:
        return False
    for rel_path, expected_hash in generated.items():
        if not isinstance(rel_path, str) or not isinstance(expected_hash, str):
            return False
        path = root / rel_path
        if not path.is_file():
            return False
        if _sha256_bytes(path.read_bytes()) != expected_hash:
            return False
    return True


def _sync_result_from_lock(project_root: Path, *, synced: bool) -> AgentInstructionSyncResult:
    root = project_root.resolve()
    lock = read_json(agent_instructions_lock_path(root), default={})
    generated = lock.get("generated_sha256", {}) if isinstance(lock, dict) else {}
    if not isinstance(generated, dict):
        generated = {}
    source = project_rules_path(root)
    project_rules = read_text(source).strip()
    return AgentInstructionSyncResult(
        synced=synced,
        source_path=_relative_path(root, source),
        source_sha256=str(lock.get("source_sha256", "")) if isinstance(lock, dict) else "",
        generated_sha256={str(key): str(value) for key, value in generated.items()},
        project_rules_meaningful=_meaningful_project_rules(project_rules),
    )


def _render_generated_files(project_rules: str) -> Dict[str, str]:
    extracted = _extract_project_rules(project_rules)
    return {
        "AGENTS.md": _limit_markdown(
            _join_sections(
                GENERATED_NOTICE,
                DEFAULT_ENGINEERING_RULES.strip(),
                _agents_project_summary(extracted),
            ),
            MAX_ROOT_AGENTS_CHARS,
        ),
        ".github/copilot-instructions.md": _limit_markdown(
            _join_sections(
                GENERATED_NOTICE,
                COPILOT_ROOT_RULES.strip(),
                _copilot_project_summary(extracted),
            ),
            MAX_COPILOT_ROOT_CHARS,
        ),
        ".github/instructions/product-contract.instructions.md": _limit_markdown(
            _join_sections(
                GENERATED_NOTICE,
                PRODUCT_CONTRACT_HEADER.strip(),
                _product_contract_instructions(extracted),
            ),
            MAX_PROJECT_INSTRUCTIONS_CHARS,
        ),
    }


def _remove_legacy_generated_files(root: Path) -> None:
    for rel_path in LEGACY_GENERATED_AGENT_INSTRUCTION_PATHS:
        path = root / rel_path
        if not path.is_file():
            continue
        if GENERATED_NOTICE not in read_text(path):
            continue
        path.unlink()


def _agents_project_summary(extracted: Dict[str, List[str]]) -> str:
    bullets = _merge_unique(
        extracted["must"],
        extracted["workflow"][:4],
        extracted["testing"][:3],
        limit=10,
    )
    if not bullets:
        return "# Project-Specific Rules\n\nNo project-specific rules are currently defined."
    return _rule_section(
        "# Project-Specific Rules",
        bullets,
        footer="See `.auto-agents/project-rules.md` for the human-readable source.",
    )


def _copilot_project_summary(extracted: Dict[str, List[str]]) -> str:
    bullets = _merge_unique(extracted["must"], extracted["workflow"][:3], limit=7)
    if not bullets:
        return "Project-specific rules are not currently defined."
    return _rule_section("Project-specific rules:", bullets)


def _product_contract_instructions(extracted: Dict[str, List[str]]) -> str:
    if not any(extracted.values()):
        return "No project-specific product contract is currently defined."
    sections = [
        _rule_section("## Hard Rules", extracted["must"][:8]),
        _rule_section("## Workflow Contracts", extracted["workflow"][:8]),
        _rule_section("## Engineering Validation", extracted["validation"][:6]),
        _rule_section("## Testing Contracts", extracted["testing"][:6]),
    ]
    return _join_sections(*sections)


def _extract_project_rules(project_rules: str) -> Dict[str, List[str]]:
    rules = {"must": [], "workflow": [], "validation": [], "testing": []}
    if not project_rules.strip():
        return rules

    for candidate in _candidate_rule_lines(project_rules):
        normalized = _normalize_rule(candidate)
        if not normalized:
            continue
        category = _rule_category(normalized)
        if category:
            _append_unique(rules[category], normalized)
        if _is_hard_rule(normalized):
            _append_unique(rules["must"], normalized)

    for key, limit in (("must", 10), ("workflow", 10), ("validation", 8), ("testing", 8)):
        rules[key] = rules[key][:limit]
    return rules


def _candidate_rule_lines(project_rules: str) -> List[str]:
    candidates: List[str] = []
    for raw_line in project_rules.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("```"):
            continue
        if re.match(r"^#{1,6}\s+", line):
            continue
        if line.startswith(("- ", "* ")):
            candidates.append(line[2:].strip())
            continue
        if re.match(r"^\d+[.)]\s+", line):
            candidates.append(re.sub(r"^\d+[.)]\s+", "", line).strip())
            continue
        candidates.extend(_split_rule_sentences(line))
    return candidates


def _split_rule_sentences(line: str) -> List[str]:
    if "|" in line and line.count("|") >= 2:
        return []
    parts = re.split(r"(?<=[。！？；.!?;])\s+|(?<=[。！？；])", line)
    return [part.strip() for part in parts if part.strip()]


def _normalize_rule(value: str) -> str:
    text = re.sub(r"`([^`]+)`", r"\1", value.strip())
    text = re.sub(r"\*\*([^*]+)\*\*", r"\1", text)
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    text = re.sub(r"\s+", " ", text).strip(" -:\t\r\n")
    if not _looks_like_instruction(text):
        return ""
    if len(text) > MAX_RULE_CHARS:
        text = text[: MAX_RULE_CHARS - 3].rstrip() + "..."
    return text


def _looks_like_instruction(text: str) -> bool:
    if len(text) < 8:
        return False
    lowered = text.lower()
    markers = (
        "must", "should", "shall", "only", "never", "default", "require", "avoid",
        "keep", "do not", "don't", "fail", "pass", "block", "review", "export",
        "test", "verify", "contract", "必须", "应该", "只能", "不要", "不能", "不再",
        "默认", "保留", "去掉", "审核", "校验", "导出", "确认", "测试", "合同",
    )
    return any(marker in lowered or marker in text for marker in markers)


def _rule_category(text: str) -> str:
    lowered = text.lower()
    if any(marker in lowered or marker in text for marker in (
        "test", "verify", "acceptance", "pytest", "测试", "验证", "断言", "期望",
    )):
        return "testing"
    if any(marker in lowered or marker in text for marker in (
        "validation", "validate", "artifact", "file", "json", "format", "工程校验", "校验",
        "产物", "结构", "文件", "格式",
    )):
        return "validation"
    if any(marker in lowered or marker in text for marker in (
        "workflow", "state", "compose", "export", "review", "confirm", "moderation",
        "pipeline", "input", "output", "流程", "状态", "审核", "确认", "导出", "合成",
        "输入", "输出",
    )):
        return "workflow"
    return ""


def _is_hard_rule(text: str) -> bool:
    lowered = text.lower()
    return any(marker in lowered or marker in text for marker in (
        "must", "must not", "never", "only", "default", "do not", "don't", "require",
        "必须", "只能", "不要", "不能", "不再", "默认",
    ))


def _append_unique(values: List[str], value: str) -> None:
    if value and value not in values:
        values.append(value)


def _merge_unique(*groups: Sequence[str], limit: int) -> List[str]:
    merged: List[str] = []
    for group in groups:
        for value in group:
            _append_unique(merged, value)
            if len(merged) >= limit:
                return merged
    return merged


def _rule_section(title: str, rules: Sequence[str], footer: str = "") -> str:
    if not rules:
        return ""
    body = "\n".join(f"- {rule}" for rule in rules)
    if footer:
        body += f"\n\n{footer}"
    return f"{title}\n\n{body}"


def _limit_markdown(content: str, max_chars: int) -> str:
    if len(content) <= max_chars:
        return content
    lines: List[str] = []
    current = 0
    for line in content.splitlines():
        projected = current + len(line) + 1
        if projected > max_chars - 80:
            break
        lines.append(line)
        current = projected
    lines.append("")
    lines.append("Content trimmed by auto_agents to keep provider instruction files concise.")
    return "\n".join(lines).rstrip() + "\n"


def _meaningful_project_rules(value: str) -> bool:
    text = value.strip()
    if not text:
        return False
    lowered = text.lower().strip("#-*` \t\r\n")
    if lowered in {"todo", "test", "tbd", "none", "n/a", "na", "placeholder"}:
        return False
    if len(re.sub(r"\s+", "", text)) >= 20:
        return True
    if re.search(r"[\u4e00-\u9fff]", text) and re.search(r"[。；，、：]|[\n-]", text):
        return True
    if len(re.findall(r"[A-Za-z][A-Za-z0-9_-]+", text)) >= 3:
        return True
    if re.search(r"^#{1,6}\s+\S+", text, flags=re.MULTILINE):
        return True
    if re.search(r"^\s*[-*]\s+\S+", text, flags=re.MULTILINE):
        return True
    return False


def _join_sections(*sections: str) -> str:
    return "\n\n".join(section.rstrip() for section in sections if section.strip()) + "\n"


def _sha256_text(value: str) -> str:
    return _sha256_bytes(value.encode("utf-8"))


def _sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def _relative_path(root: Path, path: Path) -> str:
    try:
        return str(path.resolve().relative_to(root.resolve()))
    except ValueError:
        return str(path)
