from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Sequence

from .config import agent_instructions_lock_path, normalized_project_rules_path, project_rules_path
from .io_utils import read_json, read_text, write_json, write_text
from .frontend_design import (
    frontend_design_contract_sha256,
    load_frontend_design_lock,
    validate_frontend_design_artifacts,
)


GENERATOR_VERSION = 2
MANAGED_BEGIN = "<!-- auto_agents:instructions:start -->"
MANAGED_END = "<!-- auto_agents:instructions:end -->"
COMPLETE_RULES_PATH = ".auto-agents/project-rules.agent.md"
MAX_ROOT_AGENTS_CHARS = 2800
MAX_COPILOT_ROOT_CHARS = 1800
MAX_PROJECT_INSTRUCTIONS_CHARS = 5200
MAX_RULE_CHARS = 220
NORMALIZED_RULE_KEYS = (
    "hard_rules",
    "workflow_contracts",
    "engineering_validation",
    "testing_contracts",
)


DEFAULT_ENGINEERING_RULES = """# Project Agent Instructions

- Treat this repository as the editable project unless explicitly authorized otherwise.
- Prefer small, directly verifiable changes; inspect nearby code and tests first.
- Preserve user changes and unrelated work.
- Keep runtime data under ignored temp/data directories.
- Prove changed behavior with focused tests; reuse sufficient existing coverage.
- auto_agents owns managed verification_refs and broad suites. Outside managed stages, run focused verification first.
- Resolve disagreements between tests and behavior from the approved product contract.
- Additional path-specific rules may exist in `.github/instructions/`.
"""


COPILOT_ROOT_RULES = DEFAULT_ENGINEERING_RULES


PRODUCT_CONTRACT_HEADER = """---
applyTo: "**"
---

# Product Contract Rules
"""


GENERATED_NOTICE = "<!-- Generated by auto_agents sync-agent-instructions. Edit .auto-agents/project-rules.md instead. -->"
GENERATED_AGENT_INSTRUCTION_PATHS = (
    "AGENTS.md",
    "CLAUDE.md",
    ".agents/rules/auto-agents.md",
    COMPLETE_RULES_PATH,
    ".github/copilot-instructions.md",
    ".github/instructions/product-contract.instructions.md",
)
LEGACY_GENERATED_AGENT_INSTRUCTION_PATHS = (
    ".github/instructions/project.instructions.md",
)


@dataclass(frozen=True)
class AgentInstructionSyncResult:
    synced: bool
    source_path: str
    source_sha256: str
    generated_sha256: Dict[str, str]
    project_rules_meaningful: bool

    def to_dict(self) -> dict:
        return {
            "synced": self.synced,
            "source_path": self.source_path,
            "source_sha256": self.source_sha256,
            "generated_sha256": dict(self.generated_sha256),
            "project_rules_meaningful": self.project_rules_meaningful,
        }


def project_rules_source_sha256(project_root: Path) -> str:
    source = project_rules_path(project_root.resolve())
    if not source.exists():
        return _sha256_bytes(b"")
    return _sha256_bytes(source.read_bytes())


def project_rules_are_meaningful(project_root: Path) -> bool:
    return _meaningful_project_rules(read_text(project_rules_path(project_root.resolve())).strip())


def normalized_project_rules_current(project_root: Path) -> bool:
    root = project_root.resolve()
    normalized_path = normalized_project_rules_path(root)
    if load_current_normalized_project_rules(root) is None:
        return False

    lock = read_json(agent_instructions_lock_path(root), default={})
    generated = lock.get("generated_sha256", {}) if isinstance(lock, dict) else {}
    if not isinstance(generated, dict):
        return False

    rel_path = _relative_path(root, normalized_path)
    expected_hash = generated.get(rel_path)
    if expected_hash is None:
        return True
    return normalized_path.is_file() and _sha256_bytes(normalized_path.read_bytes()) == str(expected_hash)


def load_current_normalized_project_rules(project_root: Path) -> Optional[Dict[str, List[str]]]:
    root = project_root.resolve()
    source_sha = project_rules_source_sha256(root)
    try:
        payload = read_json(normalized_project_rules_path(root), default=None)
    except (OSError, json.JSONDecodeError):
        return None
    if not isinstance(payload, dict):
        return None
    if str(payload.get("source_sha256", "")) != source_sha:
        return None
    rules = normalize_project_rules_payload(payload)
    if rules is None:
        return None
    return rules


def write_normalized_project_rules(
    project_root: Path,
    *,
    source_sha256: str,
    rules: Dict[str, List[str]],
) -> None:
    payload = {
        "source_sha256": source_sha256,
        "rules": {key: list(rules.get(key, [])) for key in NORMALIZED_RULE_KEYS},
    }
    write_json(normalized_project_rules_path(project_root.resolve()), payload)


def normalize_project_rules_payload(payload: object) -> Optional[Dict[str, List[str]]]:
    if not isinstance(payload, dict):
        return None
    raw_rules = payload.get("rules", payload)
    if not isinstance(raw_rules, dict):
        return None
    normalized: Dict[str, List[str]] = {}
    for key in NORMALIZED_RULE_KEYS:
        value = raw_rules.get(key, [])
        if not isinstance(value, list):
            return None
        items = []
        for item in value:
            text = str(item).strip()
            if text and text not in items:
                items.append(text)
        normalized[key] = items
    return normalized


def parse_normalized_project_rules_output(text: str) -> Dict[str, List[str]]:
    payload = _loads_json_object(text)
    normalized = normalize_project_rules_payload(payload)
    if normalized is None:
        raise ValueError(
            "normalized project rules must be a JSON object with rules.hard_rules, "
            "rules.workflow_contracts, rules.engineering_validation, and rules.testing_contracts arrays"
        )
    return normalized


def normalized_project_rules_identifier_feedback(
    *,
    source_text: str,
    rules: Dict[str, List[str]],
) -> Optional[str]:
    source_identifiers = _code_like_identifiers(source_text)

    introduced: List[str] = []
    for items in rules.values():
        for item in items:
            for identifier in _code_like_identifiers(item):
                if identifier not in source_identifiers and identifier not in introduced:
                    introduced.append(identifier)

    if not introduced:
        return None
    preview = ", ".join(introduced[:8])
    if len(introduced) > 8:
        preview += f", +{len(introduced) - 8} more"
    return (
        "normalized project rules introduced code-like identifiers that do not appear "
        f"in the source document: {preview}. Preserve source identifiers verbatim; "
        "do not infer, translate, rename, or invent implementation identifiers."
    )


def ensure_agent_instructions_synced(project_root: Path) -> AgentInstructionSyncResult:
    if _agent_instructions_current(project_root):
        return _sync_result_from_lock(project_root, synced=False)
    return sync_agent_instructions(project_root)


def sync_agent_instructions(
    project_root: Path,
    *,
    normalized_rules: Optional[Dict[str, List[str]]] = None,
) -> AgentInstructionSyncResult:
    root = project_root.resolve()
    source = project_rules_path(root)
    if not source.exists():
        write_text(source, "")

    raw_rules = read_text(source)
    project_rules = raw_rules.strip()
    meaningful = _meaningful_project_rules(project_rules)
    normalized_path = normalized_project_rules_path(root)
    if not meaningful and normalized_path.is_file():
        normalized_path.unlink()
    if normalized_rules is None:
        normalized_rules = (
            load_current_normalized_project_rules(root)
            if meaningful
            else None
        )
    if normalized_rules is None:
        normalized_rules = _extract_project_rules(project_rules if meaningful else "")
    rendered_rules = {key: list(normalized_rules.get(key, [])) for key in NORMALIZED_RULE_KEYS}
    frontend_lock = load_frontend_design_lock(root)
    frontend_contract_sha = _frontend_contract_sha_for_instructions(
        root,
        frontend_lock,
    )
    if frontend_contract_sha:
        rendered_rules["workflow_contracts"].extend(
            [
                "Frontend appearance and interactions must follow the approved DESIGN.md and .auto-agents/docs/frontend_prototype/manifest.json artifacts.",
                "Do not modify DESIGN.md, the approved frontend prototype artifacts, or .auto-agents/state/frontend_design.lock.json during implementation; use an explicit prototype redesign workflow instead.",
                "DESIGN.md governs visual appearance only; behavioral scope remains governed by the product spec and requirements trace.",
            ]
        )
    generated_files = _render_generated_files(rendered_rules)
    previous_lock = read_json(agent_instructions_lock_path(root), default={})
    previous_hashes = previous_lock.get("generated_sha256", {}) if isinstance(previous_lock, dict) else {}

    generated_sha256: Dict[str, str] = {}
    replacements = {}
    for rel_path, content in generated_files.items():
        path = root / rel_path
        existing = read_text(path) if path.is_file() else ""
        original = existing
        if content.startswith("---\n"):
            end = content.index("\n---\n", 4) + 5
            frontmatter, content = content[:end], content[end:]
            if existing.startswith("---\n"):
                old_end = existing.find("\n---\n", 4)
                if old_end >= 0:
                    # Keep manually authored path/activation constraints; migrate owned files.
                    owned = _sha256_text(existing) == previous_hashes.get(rel_path, "")
                    old_front = existing[:old_end + 5]
                    if not owned:
                        frontmatter = old_front
                    existing = existing[old_end + 5:]
                    expected = _sha256_text(existing) if owned else ""
                else:
                    expected = ""
            else:
                expected = previous_hashes.get(rel_path, "")
            content = frontmatter + _merge_managed_content(existing, content, expected)
        else:
            content = _merge_managed_content(existing, content, previous_hashes.get(rel_path, ""))
        if original != content:
            replacements[path] = content
        generated_sha256[rel_path] = _sha256_text(content)
    for path, content in replacements.items():
        write_text(path, content)
    if normalized_path.is_file() and load_current_normalized_project_rules(root) is not None:
        generated_sha256[_relative_path(root, normalized_path)] = _sha256_bytes(normalized_path.read_bytes())
    _remove_legacy_generated_files(root)

    source_sha = _sha256_bytes(source.read_bytes() if source.exists() else b"")
    lock_payload = {
        "generator_version": GENERATOR_VERSION,
        "generator_policy_hash": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        "source_sha256": source_sha,
        "frontend_design_contract_sha256": frontend_contract_sha,
        "generated_sha256": generated_sha256,
    }
    write_json(agent_instructions_lock_path(root), lock_payload)
    return AgentInstructionSyncResult(
        synced=True,
        source_path=_relative_path(root, source),
        source_sha256=source_sha,
        generated_sha256=generated_sha256,
        project_rules_meaningful=meaningful,
    )


def _frontend_contract_sha_for_instructions(
    project_root: Path,
    frontend_lock: object,
) -> str:
    if not isinstance(frontend_lock, dict):
        return ""
    status = str(frontend_lock.get("status", "")).strip()
    pending_reapproval = bool(
        status == "pending_approval"
        and str(frontend_lock.get("redesign_requested_at", "")).strip()
    )
    if status != "approved" and not pending_reapproval:
        return ""
    if validate_frontend_design_artifacts(
        project_root,
        frontend_lock,
        require_approved=False,
    ):
        return ""
    expected = str(frontend_lock.get("contract_sha256", "")).strip()
    return expected or frontend_design_contract_sha256(frontend_lock)


def _loads_json_object(text: str) -> object:
    stripped = str(text or "").strip()
    if not stripped:
        raise ValueError("normalized project rules output is empty")
    try:
        return json.loads(stripped)
    except json.JSONDecodeError:
        pass

    fenced = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", stripped, flags=re.DOTALL)
    if fenced:
        return json.loads(fenced.group(1))

    start = stripped.find("{")
    end = stripped.rfind("}")
    if start >= 0 and end > start:
        return json.loads(stripped[start : end + 1])
    raise ValueError("normalized project rules output did not contain a JSON object")


_BACKTICK_IDENTIFIER_RE = re.compile(r"`([^`\n]+)`")
_SEPARATOR_IDENTIFIER_RE = re.compile(
    r"(?<![A-Za-z0-9_])"
    r"(?:\.?[A-Za-z0-9][A-Za-z0-9]*(?:[._/-][A-Za-z0-9][A-Za-z0-9]*)+)"
    r"(?![A-Za-z0-9_])"
)


def _code_like_identifiers(text: str) -> set[str]:
    identifiers: set[str] = set()
    for raw in _BACKTICK_IDENTIFIER_RE.findall(str(text or "")):
        candidate = raw.strip()
        if _is_code_like_identifier(candidate, from_backtick=True):
            identifiers.add(candidate)
        for nested in _SEPARATOR_IDENTIFIER_RE.findall(candidate):
            if _is_code_like_identifier(nested, from_backtick=True):
                identifiers.add(nested)
    for candidate in _SEPARATOR_IDENTIFIER_RE.findall(str(text or "")):
        if _is_code_like_identifier(candidate):
            identifiers.add(candidate)
    return identifiers


def _is_code_like_identifier(candidate: str, *, from_backtick: bool = False) -> bool:
    value = str(candidate or "").strip().strip(".,;:()[]{}<>\"'")
    if not value or " " in value:
        return False
    if not re.search(r"[A-Za-z]", value):
        return False
    if value.startswith(("http://", "https://")):
        return False
    if not from_backtick and "-" in value and not any(marker in value for marker in ("_", ".", "/")):
        return False
    return bool(_SEPARATOR_IDENTIFIER_RE.fullmatch(value))


def _agent_instructions_current(project_root: Path) -> bool:
    root = project_root.resolve()
    source = project_rules_path(root)
    lock = read_json(agent_instructions_lock_path(root), default=None)
    if not isinstance(lock, dict) or lock.get("generator_version") != GENERATOR_VERSION:
        return False
    if lock.get("generator_policy_hash") != hashlib.sha256(Path(__file__).read_bytes()).hexdigest():
        return False
    if not source.exists():
        return False

    source_sha = _sha256_bytes(source.read_bytes())
    if str(lock.get("source_sha256", "")) != source_sha:
        return False
    frontend_lock = load_frontend_design_lock(root)
    frontend_contract_sha = _frontend_contract_sha_for_instructions(
        root,
        frontend_lock,
    )
    if str(lock.get("frontend_design_contract_sha256", "")) != frontend_contract_sha:
        return False

    generated = lock.get("generated_sha256", {})
    if not isinstance(generated, dict) or not generated:
        return False
    if not set(GENERATED_AGENT_INSTRUCTION_PATHS).issubset(generated):
        return False
    for rel_path, expected_hash in generated.items():
        if not isinstance(rel_path, str) or not isinstance(expected_hash, str):
            return False
        path = root / rel_path
        if not path.is_file():
            return False
        if _sha256_bytes(path.read_bytes()) != expected_hash:
            return False
    return True


def _sync_result_from_lock(project_root: Path, *, synced: bool) -> AgentInstructionSyncResult:
    root = project_root.resolve()
    lock = read_json(agent_instructions_lock_path(root), default={})
    generated = lock.get("generated_sha256", {}) if isinstance(lock, dict) else {}
    if not isinstance(generated, dict):
        generated = {}
    source = project_rules_path(root)
    project_rules = read_text(source).strip()
    return AgentInstructionSyncResult(
        synced=synced,
        source_path=_relative_path(root, source),
        source_sha256=str(lock.get("source_sha256", "")) if isinstance(lock, dict) else "",
        generated_sha256={str(key): str(value) for key, value in generated.items()},
        project_rules_meaningful=_meaningful_project_rules(project_rules),
    )


def _merge_managed_content(existing: str, generated: str, expected_hash: str) -> str:
    block = MANAGED_BEGIN + "\n" + generated.strip() + "\n" + MANAGED_END + "\n"
    if not existing or (expected_hash and _sha256_text(existing) == expected_hash
                        and MANAGED_BEGIN not in existing):
        return block
    if MANAGED_BEGIN in existing or MANAGED_END in existing:
        if existing.count(MANAGED_BEGIN) != 1 or existing.count(MANAGED_END) != 1:
            raise ValueError("Ambiguous auto_agents instruction boundaries; preserve the file and repair its managed markers")
        start, end = existing.index(MANAGED_BEGIN), existing.index(MANAGED_END)
        if end < start:
            raise ValueError("Invalid auto_agents instruction boundary order")
        end += len(MANAGED_END)
        if existing[end:end + 1] == "\n":
            end += 1
        return existing[:start] + block + existing[end:]
    # A file not known to the generation lock belongs to its author.
    return existing.rstrip() + "\n\n" + block


def _render_generated_files(extracted: Dict[str, List[str]]) -> Dict[str, str]:
    internal = _internal_rule_categories(extracted)
    reference = (
        "Full project contract: read .auto-agents/project-rules.agent.md when working on this project. "
        "The complete rules retain priority over abbreviated summaries. "
        "Current stage instructions specify artifact ownership and managed verification responsibilities."
    )
    root = _limit_markdown(_join_sections(DEFAULT_ENGINEERING_RULES.strip(),
        _agents_project_summary(internal)), MAX_COPILOT_ROOT_CHARS - 500)
    root = _join_sections(root, reference)
    full = _join_sections("# Complete Project Contract", *[
        _rule_section(title, extracted.get(key, []))
        for key, title in (
            ("hard_rules", "## Hard Rules"),
            ("workflow_contracts", "## Workflow Contracts"),
            ("engineering_validation", "## Engineering Validation"),
            ("testing_contracts", "## Testing Contracts"),
        )
    ])
    return {
        "AGENTS.md": root,
        "CLAUDE.md": root,
        ".github/copilot-instructions.md": root,
        ".github/instructions/product-contract.instructions.md": _join_sections(
            PRODUCT_CONTRACT_HEADER.strip(), reference),
        ".agents/rules/auto-agents.md": "---\ntrigger: always_on\n---\n\n" + root,
        COMPLETE_RULES_PATH: full,
    }


def _internal_rule_categories(rules: Dict[str, List[str]]) -> Dict[str, List[str]]:
    return {
        "must": list(rules.get("hard_rules", [])),
        "workflow": list(rules.get("workflow_contracts", [])),
        "validation": list(rules.get("engineering_validation", [])),
        "testing": list(rules.get("testing_contracts", [])),
    }


def _remove_legacy_generated_files(root: Path) -> None:
    for rel_path in LEGACY_GENERATED_AGENT_INSTRUCTION_PATHS:
        path = root / rel_path
        if not path.is_file():
            continue
        if GENERATED_NOTICE not in read_text(path):
            continue
        path.unlink()


def _agents_project_summary(extracted: Dict[str, List[str]]) -> str:
    bullets = _merge_unique(
        _priority_rules(extracted["must"], limit=7),
        _priority_rules(extracted["workflow"], limit=4),
        _priority_rules(extracted["testing"], limit=3),
        extracted["must"],
        limit=10,
    )
    if not bullets:
        return "# Project-Specific Rules\n\nNo project-specific rules are currently defined."
    return _rule_section("# Project-Specific Rules", bullets)


def _copilot_project_summary(extracted: Dict[str, List[str]]) -> str:
    bullets = _merge_unique(
        _priority_rules(extracted["must"], limit=5),
        _priority_rules(extracted["workflow"], limit=3),
        extracted["must"],
        limit=7,
    )
    if not bullets:
        return "Project-specific rules are not currently defined."
    return _rule_section("Project-specific rules:", bullets)


def _product_contract_instructions(extracted: Dict[str, List[str]]) -> str:
    if not any(extracted.values()):
        return "No project-specific product contract is currently defined."
    sections = [
        _rule_section("## Hard Rules", _priority_rules(extracted["must"], limit=12)),
        _rule_section("## Workflow Contracts", _priority_rules(extracted["workflow"], limit=12)),
        _rule_section("## Engineering Validation", _priority_rules(extracted["validation"], limit=10)),
        _rule_section("## Testing Contracts", _priority_rules(extracted["testing"], limit=8)),
    ]
    return _join_sections(*sections)


def _priority_rules(rules: Sequence[str], *, limit: int) -> List[str]:
    return _merge_unique(
        [rule for rule in rules if _high_priority_rule(rule)],
        rules,
        limit=limit,
    )


def _high_priority_rule(rule: str) -> bool:
    lowered = rule.lower()
    markers = (
        "default", "direct", "transition", "state", "mode", "must", "only",
        "never", "do not", "enum", "result", "test", "assert", "->",
        "默认", "直接", "状态", "模式", "必须", "只能", "不要", "不能",
        "不再", "结果", "测试", "断言",
    )
    return any(marker in lowered or marker in rule for marker in markers)


def _extract_project_rules(project_rules: str) -> Dict[str, List[str]]:
    rules = {
        "hard_rules": [],
        "workflow_contracts": [],
        "engineering_validation": [],
        "testing_contracts": [],
    }
    if not project_rules.strip():
        return rules

    for candidate in _candidate_rule_lines(project_rules):
        normalized = _normalize_rule(candidate)
        if not normalized:
            continue
        category = _rule_category(normalized)
        if category:
            _append_unique(rules[category], normalized)
        if _is_hard_rule(normalized):
            _append_unique(rules["hard_rules"], normalized)

    return rules


def _candidate_rule_lines(project_rules: str) -> List[str]:
    candidates: List[str] = []
    lines = project_rules.splitlines()
    index = 0
    while index < len(lines):
        raw_line = lines[index]
        line = raw_line.strip()
        if not line or line.startswith("```"):
            index += 1
            continue
        if re.match(r"^#{1,6}\s+", line):
            index += 1
            continue
        if line.startswith(("- ", "* ")):
            candidates.append(line[2:].strip())
            index += 1
            continue
        if re.match(r"^\d+[.)]\s+", line):
            candidates.append(re.sub(r"^\d+[.)]\s+", "", line).strip())
            index += 1
            continue
        if _has_following_list(lines, index) and not _is_structural_intro(line):
            intro, consumed = _consume_list_intro(lines, index)
            if intro:
                candidates.append(intro)
                index = consumed
                continue
            index += 1
            continue
        if _is_structural_intro(line):
            index += 1
            continue
        candidates.extend(_split_rule_sentences(line))
        index += 1
    return candidates


def _has_following_list(lines: List[str], index: int) -> bool:
    line = lines[index].strip()
    if not line.endswith((":", "：")):
        return False
    cursor = index + 1
    while cursor < len(lines):
        next_line = lines[cursor].strip()
        if not next_line:
            cursor += 1
            continue
        return next_line.startswith(("- ", "* "))
    return False


def _consume_list_intro(lines: List[str], index: int) -> tuple[str, int]:
    intro = lines[index].strip().rstrip(":：")
    values: List[str] = []
    cursor = index + 1
    while cursor < len(lines):
        line = lines[cursor].strip()
        if not line:
            cursor += 1
            continue
        if re.match(r"^#{1,6}\s+", line):
            break
        if not line.startswith(("- ", "* ")):
            break
        value = line[2:].strip()
        if value:
            values.append(_inline_code_to_plain(value))
        cursor += 1
    if not values:
        return "", index + 1
    return f"{intro}: {', '.join(values)}", cursor


def _is_structural_intro(line: str) -> bool:
    stripped = line.strip()
    if not stripped.endswith((":", "：")):
        return False
    lowered = stripped.lower()
    structural_markers = (
        "如下", "关注", "不在本文档", "原因", "建议输入", "也就是说",
        "examples", "example", "for example",
    )
    return any(marker in lowered or marker in stripped for marker in structural_markers)


def _split_rule_sentences(line: str) -> List[str]:
    if "|" in line and line.count("|") >= 2:
        return []
    parts = re.split(r"(?<=[。！？；.!?;])\s+|(?<=[。！？；])", line)
    return [part.strip() for part in parts if part.strip()]


def _normalize_rule(value: str) -> str:
    text = _inline_code_to_plain(value.strip())
    text = re.sub(r"\*\*([^*]+)\*\*", r"\1", text)
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    text = re.sub(r"\s+", " ", text).strip(" -:\t\r\n")
    if text.startswith("这两步"):
        text = "输入审核和输出审核" + text[len("这两步"):]
    if not _looks_like_instruction(text):
        return ""
    return text


def _inline_code_to_plain(value: str) -> str:
    return re.sub(r"`([^`]+)`", r"\1", value)


def _looks_like_instruction(text: str) -> bool:
    if len(text) < 8:
        return False
    if "当前用户真正关心" in text:
        return False
    if " / " in text and "边界" in text:
        return False
    if _looks_like_stage_label(text):
        return False
    lowered = text.lower()
    markers = (
        "must", "should", "shall", "only", "never", "default", "require", "avoid",
        "keep", "do not", "don't",
        "test", "verify", "contract", "必须", "应该", "只能", "不要", "不能", "不再",
        "默认", "保留", "去掉", "审核", "校验", "导出", "确认", "测试", "合同",
    )
    return any(marker in lowered or marker in text for marker in markers)


def _looks_like_stage_label(text: str) -> bool:
    if any(char in text for char in "，。；：:,.!?！？"):
        return False
    words = re.findall(r"[A-Za-z_][A-Za-z0-9_/-]*", text)
    has_cjk = bool(re.search(r"[\u4e00-\u9fff]", text))
    if has_cjk and len(text) <= 18 and len(words) <= 2:
        return True
    if not has_cjk and 1 <= len(words) <= 3:
        return True
    return False


def _rule_category(text: str) -> str:
    lowered = text.lower()
    if any(marker in lowered or marker in text for marker in (
        "test", "verify", "acceptance", "pytest", "测试", "验证", "断言", "期望",
    )):
        return "testing_contracts"
    if any(marker in lowered or marker in text for marker in (
        "validation", "validate", "artifact", "file", "json", "format", "工程校验", "校验",
        "产物", "结构", "文件", "格式",
    )):
        return "engineering_validation"
    if any(marker in lowered or marker in text for marker in (
        "workflow", "state", "compose", "export", "review", "confirm", "moderation",
        "pipeline", "input", "output", "流程", "状态", "审核", "确认", "导出", "合成",
        "输入", "输出",
    )):
        return "workflow_contracts"
    return ""


def _is_hard_rule(text: str) -> bool:
    lowered = text.lower()
    return any(marker in lowered or marker in text for marker in (
        "must", "must not", "never", "only", "default", "do not", "don't", "require",
        "必须", "只能", "不要", "不能", "不再", "默认",
    ))


def _append_unique(values: List[str], value: str) -> None:
    if value and value not in values:
        values.append(value)


def _merge_unique(*groups: Sequence[str], limit: int) -> List[str]:
    merged: List[str] = []
    for group in groups:
        for value in group:
            _append_unique(merged, value)
            if len(merged) >= limit:
                return merged
    return merged


def _rule_section(title: str, rules: Sequence[str], footer: str = "") -> str:
    if not rules:
        return ""
    body = "\n".join(f"- {rule}" for rule in rules)
    if footer:
        body += f"\n\n{footer}"
    return f"{title}\n\n{body}"


def _limit_markdown(content: str, max_chars: int) -> str:
    if len(content) <= max_chars:
        return content
    lines: List[str] = []
    current = 0
    for line in content.splitlines():
        projected = current + len(line) + 1
        if projected > max_chars - 80:
            break
        lines.append(line)
        current = projected
    lines.append("")
    lines.append("Content trimmed by auto_agents to keep provider instruction files concise.")
    return "\n".join(lines).rstrip() + "\n"


def _meaningful_project_rules(value: str) -> bool:
    text = value.strip()
    if not text:
        return False
    lowered = text.lower().strip("#-*` \t\r\n")
    if lowered in {"todo", "test", "tbd", "none", "n/a", "na", "placeholder"}:
        return False
    if len(re.sub(r"\s+", "", text)) >= 20:
        return True
    if re.search(r"[\u4e00-\u9fff]", text) and re.search(r"[。；，、：]|[\n-]", text):
        return True
    if len(re.findall(r"[A-Za-z][A-Za-z0-9_-]+", text)) >= 3:
        return True
    if re.search(r"^#{1,6}\s+\S+", text, flags=re.MULTILINE):
        return True
    if re.search(r"^\s*[-*]\s+\S+", text, flags=re.MULTILINE):
        return True
    return False


def _join_sections(*sections: str) -> str:
    return "\n\n".join(section.rstrip() for section in sections if section.strip()) + "\n"


def _sha256_text(value: str) -> str:
    return _sha256_bytes(value.encode("utf-8"))


def _sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def _relative_path(root: Path, path: Path) -> str:
    try:
        return str(path.resolve().relative_to(root.resolve()))
    except ValueError:
        return str(path)
