from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List

from .config import agent_instructions_lock_path, project_rules_path
from .io_utils import read_json, read_text, write_json, write_text


DEFAULT_ENGINEERING_RULES = """# Project Agent Instructions

These instructions apply to Codex, GitHub Copilot CLI, and other coding agents working in this repository.

## Working Rules

- Treat the current repository as the only editable project unless the user explicitly says otherwise.
- Prefer small, directly verifiable changes over broad rewrites.
- Read the nearby implementation and tests before changing behavior.
- Preserve user changes and do not revert unrelated work.
- Keep generated runtime data under ignored temp/data directories, not tracked repo-root files.
- When changing behavior, update or add focused tests that prove the intended contract.
- Run the narrowest relevant verification first; run broader verification when the change touches shared behavior.
- If tests and product behavior disagree, identify the contract first instead of blindly changing tests.
"""


COPILOT_ROOT_RULES = """# Repository Instructions

- Work only inside this repository unless the user explicitly says otherwise.
- Keep changes focused and consistent with nearby code.
- Preserve unrelated user edits.
- Prefer owned, focused tests before broad verification.
- If a test conflicts with product behavior, resolve the product contract before changing expectations.
- Additional path-specific rules may exist in `.github/instructions/`.
"""


PROJECT_INSTRUCTIONS_HEADER = """---
applyTo: "**"
---

# Project Rules

Follow the repository rules in `AGENTS.md`. The project-specific rules below come from `.auto-agents/project-rules.md`.
"""


GENERATED_NOTICE = "<!-- Generated by auto_agents sync-agent-instructions. Edit .auto-agents/project-rules.md instead. -->"
GENERATED_AGENT_INSTRUCTION_PATHS = (
    "AGENTS.md",
    ".github/copilot-instructions.md",
    ".github/instructions/project.instructions.md",
)


@dataclass(frozen=True)
class AgentInstructionSyncResult:
    synced: bool
    source_path: str
    source_sha256: str
    generated_sha256: Dict[str, str]
    project_rules_meaningful: bool

    def to_dict(self) -> dict:
        return {
            "synced": self.synced,
            "source_path": self.source_path,
            "source_sha256": self.source_sha256,
            "generated_sha256": dict(self.generated_sha256),
            "project_rules_meaningful": self.project_rules_meaningful,
        }


def ensure_agent_instructions_synced(project_root: Path) -> AgentInstructionSyncResult:
    if _agent_instructions_current(project_root):
        return _sync_result_from_lock(project_root, synced=False)
    return sync_agent_instructions(project_root)


def sync_agent_instructions(project_root: Path) -> AgentInstructionSyncResult:
    root = project_root.resolve()
    source = project_rules_path(root)
    if not source.exists():
        write_text(source, "")

    raw_rules = read_text(source)
    project_rules = raw_rules.strip()
    meaningful = _meaningful_project_rules(project_rules)
    generated_files = _render_generated_files(project_rules if meaningful else "")

    generated_sha256: Dict[str, str] = {}
    for rel_path, content in generated_files.items():
        path = root / rel_path
        write_text(path, content)
        generated_sha256[rel_path] = _sha256_text(content)

    source_sha = _sha256_bytes(source.read_bytes() if source.exists() else b"")
    lock_payload = {
        "source_sha256": source_sha,
        "generated_sha256": generated_sha256,
    }
    write_json(agent_instructions_lock_path(root), lock_payload)
    return AgentInstructionSyncResult(
        synced=True,
        source_path=_relative_path(root, source),
        source_sha256=source_sha,
        generated_sha256=generated_sha256,
        project_rules_meaningful=meaningful,
    )


def _agent_instructions_current(project_root: Path) -> bool:
    root = project_root.resolve()
    source = project_rules_path(root)
    lock = read_json(agent_instructions_lock_path(root), default=None)
    if not isinstance(lock, dict):
        return False
    if not source.exists():
        return False

    source_sha = _sha256_bytes(source.read_bytes())
    if str(lock.get("source_sha256", "")) != source_sha:
        return False

    generated = lock.get("generated_sha256", {})
    if not isinstance(generated, dict) or not generated:
        return False
    for rel_path, expected_hash in generated.items():
        if not isinstance(rel_path, str) or not isinstance(expected_hash, str):
            return False
        path = root / rel_path
        if not path.is_file():
            return False
        if _sha256_bytes(path.read_bytes()) != expected_hash:
            return False
    return True


def _sync_result_from_lock(project_root: Path, *, synced: bool) -> AgentInstructionSyncResult:
    root = project_root.resolve()
    lock = read_json(agent_instructions_lock_path(root), default={})
    generated = lock.get("generated_sha256", {}) if isinstance(lock, dict) else {}
    if not isinstance(generated, dict):
        generated = {}
    source = project_rules_path(root)
    project_rules = read_text(source).strip()
    return AgentInstructionSyncResult(
        synced=synced,
        source_path=_relative_path(root, source),
        source_sha256=str(lock.get("source_sha256", "")) if isinstance(lock, dict) else "",
        generated_sha256={str(key): str(value) for key, value in generated.items()},
        project_rules_meaningful=_meaningful_project_rules(project_rules),
    )


def _render_generated_files(project_rules: str) -> Dict[str, str]:
    project_section = _project_rules_section(project_rules)
    return {
        "AGENTS.md": _join_sections(
            GENERATED_NOTICE,
            DEFAULT_ENGINEERING_RULES.strip(),
            project_section,
        ),
        ".github/copilot-instructions.md": _join_sections(
            GENERATED_NOTICE,
            COPILOT_ROOT_RULES.strip(),
            _short_project_rules_section(project_rules),
        ),
        ".github/instructions/project.instructions.md": _join_sections(
            GENERATED_NOTICE,
            PROJECT_INSTRUCTIONS_HEADER.strip(),
            project_section,
        ),
    }


def _project_rules_section(project_rules: str) -> str:
    if project_rules.strip():
        return "# Project-Specific Rules\n\n" + project_rules.strip()
    return "# Project-Specific Rules\n\nNo project-specific rules are currently defined."


def _short_project_rules_section(project_rules: str) -> str:
    if not project_rules.strip():
        return "Project-specific rules are not currently defined."
    bullets = _extract_rule_bullets(project_rules, limit=8)
    if bullets:
        return "Project-specific rules:\n\n" + "\n".join(f"- {item}" for item in bullets)
    first = " ".join(project_rules.strip().split())
    if len(first) > 900:
        first = first[:897].rstrip() + "..."
    return "Project-specific rules summary:\n\n" + first


def _extract_rule_bullets(project_rules: str, *, limit: int) -> List[str]:
    bullets: List[str] = []
    for raw_line in project_rules.splitlines():
        line = raw_line.strip()
        if not line.startswith(("- ", "* ")):
            continue
        value = line[2:].strip()
        if value:
            bullets.append(value)
        if len(bullets) >= limit:
            break
    return bullets


def _meaningful_project_rules(value: str) -> bool:
    text = value.strip()
    if not text:
        return False
    lowered = text.lower().strip("#-*` \t\r\n")
    if lowered in {"todo", "test", "tbd", "none", "n/a", "na", "placeholder"}:
        return False
    if len(re.sub(r"\s+", "", text)) >= 20:
        return True
    if re.search(r"[\u4e00-\u9fff]", text) and re.search(r"[。；，、：]|[\n-]", text):
        return True
    if len(re.findall(r"[A-Za-z][A-Za-z0-9_-]+", text)) >= 3:
        return True
    if re.search(r"^#{1,6}\s+\S+", text, flags=re.MULTILINE):
        return True
    if re.search(r"^\s*[-*]\s+\S+", text, flags=re.MULTILINE):
        return True
    return False


def _join_sections(*sections: str) -> str:
    return "\n\n".join(section.rstrip() for section in sections if section.strip()) + "\n"


def _sha256_text(value: str) -> str:
    return _sha256_bytes(value.encode("utf-8"))


def _sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def _relative_path(root: Path, path: Path) -> str:
    try:
        return str(path.resolve().relative_to(root.resolve()))
    except ValueError:
        return str(path)
